//------------------------------------------------------------------------------
// <auto-generated>
//     This code was developed for PerformanceMonitor telemetry services.
// </auto-generated>
// <summary>
//     Desktop-optimized CPU Quality of Service (QoS) and topology management.
//     Streamlined for single-group processor architectures (≤ 64 logical processors)
//     typical of consumer and enthusiast gaming hardware.
// </summary>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace PerformanceMonitor
{
    /// <summary>
    /// Provides lightweight thread and process scheduling controls, including CPU Sets,
    /// EcoQoS (Power Throttling), and hard affinity management tailored for desktop processors.	
    /// In other words, Thread and process CPU quality-of-service helpers for desktop Intel and AMD processors.
    /// Supports hybrid CPUs (e.g. Intel Core i9-12700K, i9-14700K) via efficiency-class
    /// discovery, and degrades gracefully to no-ops on homogeneous CPUs (e.g. Intel Core i7-960,
    /// AMD Ryzen desktop) where <see cref="IsHybridCpu"/> returns <c>false</c>.
    /// <para>
    /// All thread-scoped methods affect only the calling thread.
    /// All processor-group logic is intentionally omitted: every supported CPU fits within
    /// a single processor group (≤ 64 logical processors), so the simpler
    /// <c>SetThreadAffinityMask</c> / <c>SetProcessAffinityMask</c> API surface is sufficient.
    /// </para>
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Architecture Overview:</b>
    /// This implementation is deliberately streamlined for consumer and enthusiast desktop 
    /// hardware (e.g., Intel Core i9, AMD Ryzen). By asserting a strict single-processor-group 
    /// environment (≤ 64 logical processors), it bypasses complex multi-group topology routing 
    /// in favor of the highly efficient <c>SetThreadAffinityMask</c> and <c>SetProcessAffinityMask</c> APIs.
    /// </para>
    /// <para>
    /// It dynamically queries the system's <c>SYSTEM_CPU_SET_INFORMATION</c> to map efficiency 
    /// classes, allowing telemetry and background threads to be seamlessly pinned to E-Cores 
    /// (Efficiency Cores) without interfering with primary foreground applications or games.
    /// </para>
    /// <para>
    /// <b>Key Capabilities:</b>
    /// <list type="bullet">
    ///     <item>
    ///         <description><b>Hybrid Awareness:</b> Discovers and targets specific efficiency classes (P-Cores vs E-Cores).</description>
    ///     </item>
    ///     <item>
    ///         <description><b>EcoQoS:</b> Invokes Windows 11/10 Power Throttling to run threads in Efficiency Mode.</description>
    ///     </item>
    ///     <item>
    ///         <description><b>Hard/Soft Affinity:</b> Restricts thread or process execution to selected hardware cores.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>
    /// <i>Hardware Constraint: This class is not intended for Workstation/Server systems 
    /// (e.g., dual-socket Xeon, Threadripper PRO) exceeding 64 logical cores.</i>
    /// </para>
    /// </remarks>	
    internal static class CPU_QoS
    {
        // ==========================================================
        // Public Enum
        // ==========================================================

        /// <summary>
        /// Selects which efficiency class of cores to target.
        /// On homogeneous CPUs (non-hybrid) all cores share one efficiency class,
        /// so <see cref="Efficiency"/> and <see cref="Performance"/> both select all cores.
        /// </summary>
        public enum CpuSetType
        {
            /// <summary>No restriction — the OS scheduler decides freely.</summary>
            None = 0,

            /// <summary>
            /// E-Cores (lowest efficiency class) on hybrid CPUs; all cores on homogeneous CPUs.
            /// </summary>
            Efficiency = 1,

            /// <summary>
            /// P-Cores (highest efficiency class) on hybrid CPUs; all cores on homogeneous CPUs.
            /// </summary>
            Performance = 2
        }

        // ==========================================================
        // Public API
        // ==========================================================

        /// <summary>
        /// Returns the pseudo-handle to the current thread.
        /// Useful for callers that need the raw handle for custom Win32 calls.
        /// </summary>
        public static IntPtr GetCurrentWinThreadHandle() => GetCurrentThread();

        /// <summary>
        /// Returns <c>true</c> when at least two distinct efficiency classes are present among
        /// the CPU sets usable by this process — indicating a hybrid CPU architecture such as
        /// the Intel Core i9-14700K (P-Cores + E-Cores).
        /// Returns <c>false</c> on homogeneous CPUs such as the Intel Core i7-960 or AMD Ryzen
        /// desktop chips, or if the topology query fails.
        /// </summary>
        public static bool IsHybridCpu()
        {
            try
            {
                var topo = QueryUsableCpuTopology();
                return topo.CpuSets.Count > 0
                    && topo.MinEfficiencyClass != topo.MaxEfficiencyClass;
            }
            catch
            {
                return false; // Safe default for unsupported or unexpected systems.
            }
        }

        /// <summary>
        /// Enables or disables EcoQoS (Efficiency Mode / Power Throttling) for the current thread.
        /// Attempts the Windows 11 API first (ThreadInformationClass 3), then falls back to the
        /// Windows 10 API (ThreadInformationClass 1) automatically.
        /// </summary>
        /// <param name="enable"><c>true</c> to enable EcoQoS; <c>false</c> to disable it.</param>
        /// <exception cref="Win32Exception">Thrown when the Win32 call fails on both API levels.</exception>
        public static void SetEcoQoS(bool enable)
        {
            var state = new THREAD_POWER_THROTTLING_STATE
            {
                Version     = THREAD_POWER_THROTTLING_CURRENT_VERSION,
                ControlMask = THREAD_POWER_THROTTLING_EXECUTION_SPEED,
                StateMask   = enable ? THREAD_POWER_THROTTLING_EXECUTION_SPEED : 0u
            };

            IntPtr hThread = GetCurrentThread();
            uint   size    = (uint)Marshal.SizeOf<THREAD_POWER_THROTTLING_STATE>();

            if (SetThreadInformation(hThread, TIC_THREAD_POWER_THROTTLING_WIN11, ref state, size))
                return;

            int err = Marshal.GetLastWin32Error();

            if (err == ERROR_INVALID_PARAMETER &&
                SetThreadInformation(hThread, TIC_THREAD_POWER_THROTTLING_WIN10, ref state, size))
                return;

            throw new Win32Exception(Marshal.GetLastWin32Error(), "Failed to set EcoQoS state.");
        }

        /// <summary>
        /// Configures CPU Sets (soft affinity hint) for the current thread from a string token.
        /// Accepts exact enum names (case-insensitive) and partial keywords:
        /// "eff" / "eco" → <see cref="CpuSetType.Efficiency"/>;
        /// "perf" → <see cref="CpuSetType.Performance"/>.
        /// Unrecognised tokens map to <see cref="CpuSetType.None"/>.
        /// </summary>
        public static void SetCpuSets(string mode)
        {
            if (string.IsNullOrWhiteSpace(mode)) { SetCpuSets(CpuSetType.None); return; }

            if (Enum.TryParse(mode, ignoreCase: true, out CpuSetType parsed))
            {
                SetCpuSets(parsed);
                return;
            }

            string m = mode.ToLowerInvariant();
            if      (m.Contains("eff") || m.Contains("eco")) SetCpuSets(CpuSetType.Efficiency);
            else if (m.Contains("perf"))                     SetCpuSets(CpuSetType.Performance);
            else                                             SetCpuSets(CpuSetType.None);
        }

        /// <summary>
        /// Configures CPU Sets (soft affinity hint) for the current thread.
        /// The OS respects this hint but may override it under extreme load.
        /// For a strict guarantee use <see cref="SetHardAffinity"/> instead.
        /// <see cref="CpuSetType.None"/> clears any existing CPU Set restriction.
        /// </summary>
        /// <exception cref="Win32Exception">Thrown when the Win32 call fails.</exception>
        public static void SetCpuSets(CpuSetType type)
        {
            IntPtr hThread = GetCurrentThread();

            if (type == CpuSetType.None)
            {
                if (!SetThreadSelectedCpuSets(hThread, null, 0))
                    throw new Win32Exception(Marshal.GetLastWin32Error(), "Failed to clear CPU Sets.");
                return;
            }

            var    topo = QueryUsableCpuTopology();
            uint[] ids  = SelectCpuSetIds(type, in topo);

            if (ids.Length > 0)
            {
                if (!SetThreadSelectedCpuSets(hThread, ids, (uint)ids.Length))
                    throw new Win32Exception(Marshal.GetLastWin32Error(), "Failed to set CPU Sets.");
            }
            else
            {
                // No matching cores (non-hybrid CPU, or all target cores unavailable).
                // Revert to unrestricted rather than leaving the thread incorrectly pinned.
                SetThreadSelectedCpuSets(hThread, null, 0);
            }
        }

        /// <summary>
        /// Sets a hard processor affinity for the <b>current thread only</b>.
        /// Strictly enforced by the OS scheduler, unlike CPU Sets.
        /// <para>
        /// <see cref="CpuSetType.None"/> resets the thread's affinity to the full process mask,
        /// removing any prior restriction.
        /// </para>
        /// </summary>
        /// <exception cref="Win32Exception">Thrown when the Win32 call fails.</exception>
        public static void SetHardAffinity(CpuSetType type)
        {
            IntPtr hThread = GetCurrentThread();

            ulong mask = type == CpuSetType.None
                ? GetProcessAffinityMaskOrThrow()
                : BuildAffinityMask(type);

            // Fallback: if no target cores found (non-hybrid CPU), use the process mask.
            if (mask == 0) mask = GetProcessAffinityMaskOrThrow();

            if (SetThreadAffinityMask(hThread, new UIntPtr(mask)) == UIntPtr.Zero)
                throw new Win32Exception(Marshal.GetLastWin32Error(), "Failed to set thread hard affinity.");
        }

        /// <summary>
        /// Sets a hard processor affinity for the <b>entire current process</b>.
        /// Every thread in the process will be constrained to the selected cores.
        /// <para>
        /// Use this only when intentionally restricting the whole application.
        /// For per-thread control prefer <see cref="SetHardAffinity"/>.
        /// </para>
        /// <para>
        /// <see cref="CpuSetType.None"/> restores the process affinity to the full system mask.
        /// </para>
        /// </summary>
        /// <exception cref="Win32Exception">Thrown when the Win32 call fails.</exception>
        public static void SetHardAffinityProcess(CpuSetType type)
        {
            IntPtr hProcess = GetCurrentProcess();

            if (!GetProcessAffinityMask(hProcess, out _, out UIntPtr systemMaskPtr))
                throw new Win32Exception(Marshal.GetLastWin32Error(), "GetProcessAffinityMask failed.");

            ulong systemMask = systemMaskPtr.ToUInt64();

            ulong mask = type == CpuSetType.None
                ? systemMask
                : BuildAffinityMask(type) & systemMask; // intersect: never exceed system mask

            // Fallback: no target cores found, restore full mask rather than deadlock all threads.
            if (mask == 0) mask = systemMask;

            if (!SetProcessAffinityMask(hProcess, new UIntPtr(mask)))
                throw new Win32Exception(Marshal.GetLastWin32Error(), "SetProcessAffinityMask failed.");
        }

        /// <summary>
        /// Returns the number of logical processors the current thread is permitted to run on —
        /// i.e. the valid index range for a future <c>SetThreadIdealProcessor()</c> call.
        /// Reflects any restriction previously applied via <see cref="SetHardAffinity"/>.
        /// </summary>
        public static int GetAvailableProcessorCount()
        {
            IntPtr hThread = GetCurrentThread();

            // GetThreadGroupAffinity gives the thread's actual current mask, already reflecting
            // any SetHardAffinity restriction applied on this thread.
            if (GetThreadGroupAffinity(hThread, out GROUP_AFFINITY ga))
                return PopCount(ga.Mask.ToUInt64());

            // Fallback: process mask (ignores thread-level restrictions, but better than nothing).
            IntPtr hProcess = GetCurrentProcess();
            if (GetProcessAffinityMask(hProcess, out UIntPtr procMask, out _))
                return PopCount(procMask.ToUInt64());

            return Math.Max(1, Environment.ProcessorCount);
        }

        // ==========================================================
        // Internal Data Structures
        // ==========================================================

        private const byte FLAG_ALLOCATED           = 0x02;
        private const byte FLAG_ALLOCATED_TO_TARGET = 0x04;

        /// <summary>
        /// Maps directly onto the CpuSet member inside SYSTEM_CPU_SET_INFORMATION.
        /// FieldOffset values verified against Windows SDK 10.0.26100 (winnt.h).
        /// Using LayoutKind.Explicit makes offsets self-documenting and compiler-checked,
        /// replacing manual Marshal.ReadByte / Marshal.ReadInt32 calls.
        /// </summary>
		/// Includes the Size = 32 fix
        [StructLayout(LayoutKind.Explicit, Size = 32)]
        private struct SYSTEM_CPU_SET_INFORMATION
        {
            [FieldOffset( 0)] public uint   Size;
            [FieldOffset( 4)] public int    Type;  // 0 = CpuSetInformation
            // CpuSet union fields:
            [FieldOffset( 8)] public uint   Id;
            [FieldOffset(12)] public ushort Group;
            [FieldOffset(14)] public byte   LogicalProcessorIndex;
            [FieldOffset(15)] public byte   CoreIndex;
            [FieldOffset(16)] public byte   LastLevelCacheIndex;
            [FieldOffset(17)] public byte   NumaNodeIndex;
            [FieldOffset(18)] public byte   EfficiencyClass;
            [FieldOffset(19)] public byte   AllFlags;
        }

        private struct InternalCpuSet
        {
            public uint Id;
            public byte LogicalProcessorIndex;
            public byte EfficiencyClass;
            public byte AllFlags;

            public bool IsUsable =>
                (AllFlags & FLAG_ALLOCATED) == 0 ||
                (AllFlags & FLAG_ALLOCATED_TO_TARGET) != 0;
        }

        /// <summary>
        /// Topology snapshot pre-filtered to cores usable by this process.
        /// Min/max efficiency classes reflect only usable cores, so IsHybridCpu()
        /// and affinity selection are always accurate for this process.
        /// </summary>
        private struct CpuSetTopology
        {
            public List<InternalCpuSet> CpuSets;
            public byte MinEfficiencyClass;
            public byte MaxEfficiencyClass;
        }

        // ==========================================================
        // Internal Helpers
        // ==========================================================

        /// <summary>
        /// Queries GetSystemCpuSetInformation and returns a pre-filtered topology snapshot.
        /// Only cores usable by this process are included.
        /// </summary>
        private static CpuSetTopology QueryUsableCpuTopology()
        {
            var topo = new CpuSetTopology
            {
                CpuSets            = new List<InternalCpuSet>(),
                MinEfficiencyClass = 255,
                MaxEfficiencyClass = 0
            };

            IntPtr hProcess = GetCurrentProcess();

            GetSystemCpuSetInformation(IntPtr.Zero, 0, out uint required, hProcess, 0);
            if (required == 0) return Normalize(topo);

            IntPtr buffer = Marshal.AllocHGlobal((int)required);
            try
            {
                if (!GetSystemCpuSetInformation(buffer, required, out required, hProcess, 0))
                    throw new Win32Exception(Marshal.GetLastWin32Error(),
                        "GetSystemCpuSetInformation failed.");

                long ptr = buffer.ToInt64();
                long end = ptr + required;

                while (ptr < end)
                {
                    var info = Marshal.PtrToStructure<SYSTEM_CPU_SET_INFORMATION>(new IntPtr(ptr));
                    if (info.Size <= 0) break;

                    if (info.Type == 0) // CpuSetInformation
                    {
                        var cpu = new InternalCpuSet
                        {
                            Id                    = info.Id,
                            LogicalProcessorIndex = info.LogicalProcessorIndex,
                            EfficiencyClass       = info.EfficiencyClass,
                            AllFlags              = info.AllFlags
                        };

                        if (cpu.IsUsable)
                        {
                            if (cpu.EfficiencyClass < topo.MinEfficiencyClass)
                                topo.MinEfficiencyClass = cpu.EfficiencyClass;
                            if (cpu.EfficiencyClass > topo.MaxEfficiencyClass)
                                topo.MaxEfficiencyClass = cpu.EfficiencyClass;

                            topo.CpuSets.Add(cpu);
                        }
                    }

                    ptr += info.Size;
                }
            }
            finally
            {
                Marshal.FreeHGlobal(buffer);
            }

            return Normalize(topo);
        }

        private static CpuSetTopology Normalize(CpuSetTopology topo)
        {
            if (topo.CpuSets.Count == 0)
                topo.MinEfficiencyClass = topo.MaxEfficiencyClass = 0;
            return topo;
        }

        /// <summary>
        /// Builds a bitmask of logical processors matching the requested efficiency class.
        /// Returns 0 when no matching cores are found.
        /// </summary>
        private static ulong BuildAffinityMask(CpuSetType type)
        {
            var topo = QueryUsableCpuTopology();
            if (topo.CpuSets.Count == 0) return 0;

            byte targetEff = type == CpuSetType.Efficiency
                ? topo.MinEfficiencyClass
                : topo.MaxEfficiencyClass;

            ulong mask = 0;
            foreach (var cpu in topo.CpuSets)
                if (cpu.EfficiencyClass == targetEff && cpu.LogicalProcessorIndex < 64)
                    mask |= 1UL << cpu.LogicalProcessorIndex;

            return mask;
        }

        /// <summary>
        /// Selects CPU Set IDs matching the requested efficiency class.
        /// Returns an empty array when no matching cores are found.
        /// </summary>
        private static uint[] SelectCpuSetIds(CpuSetType type, in CpuSetTopology topo)
        {
            if (topo.CpuSets.Count == 0) return Array.Empty<uint>();

            byte targetEff = type == CpuSetType.Efficiency
                ? topo.MinEfficiencyClass
                : topo.MaxEfficiencyClass;

            var ids = new List<uint>();
            foreach (var cpu in topo.CpuSets)
                if (cpu.EfficiencyClass == targetEff)
                    ids.Add(cpu.Id);

            return ids.ToArray();
        }

        /// <summary>Returns the process affinity mask as a ulong, or throws if the query fails.</summary>
        private static ulong GetProcessAffinityMaskOrThrow()
        {
            if (!GetProcessAffinityMask(GetCurrentProcess(), out UIntPtr mask, out _))
                throw new Win32Exception(Marshal.GetLastWin32Error(), "GetProcessAffinityMask failed.");
            return mask.ToUInt64();
        }

        /// <summary>Counts set bits in a 64-bit mask (Kernighan's algorithm).</summary>
        private static int PopCount(ulong v)
        {
            int n = 0;
            while (v != 0) { v &= v - 1; n++; }
            return n;
        }

        // ==========================================================
        // Native Structures & Constants
        // ==========================================================

        [StructLayout(LayoutKind.Sequential)]
        private struct THREAD_POWER_THROTTLING_STATE
        {
            public uint Version;
            public uint ControlMask;
            public uint StateMask;
        }

        // GROUP_AFFINITY is kept solely for GetThreadGroupAffinity(), which is the only Win32 call
        // that can read back the thread's current affinity mask without storing private state.
        // SetThreadGroupAffinity is intentionally NOT imported: SetThreadAffinityMask is sufficient
        // for all desktop CPUs with ≤ 64 logical processors (single processor group).
        [StructLayout(LayoutKind.Sequential)]
        private struct GROUP_AFFINITY
        {
            public UIntPtr Mask;
            public ushort  Group;
            public ushort  Reserved1;
            public ushort  Reserved2;
            public ushort  Reserved3;
        }

        private const uint THREAD_POWER_THROTTLING_CURRENT_VERSION = 1;
        private const uint THREAD_POWER_THROTTLING_EXECUTION_SPEED = 1;
        private const int  TIC_THREAD_POWER_THROTTLING_WIN10       = 1;
        private const int  TIC_THREAD_POWER_THROTTLING_WIN11       = 3;
        private const int  ERROR_INVALID_PARAMETER                 = 87;

        // ==========================================================
        // P/Invoke
        // ==========================================================

        [DllImport("kernel32.dll")]
        private static extern IntPtr GetCurrentThread();

        [DllImport("kernel32.dll")]
        private static extern IntPtr GetCurrentProcess();

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool SetThreadInformation(
            IntPtr hThread, int ThreadInformationClass,
            ref THREAD_POWER_THROTTLING_STATE ThreadInformation,
            uint ThreadInformationSize);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetSystemCpuSetInformation(
            IntPtr Information, uint BufferLength,
            out uint ReturnedLength, IntPtr Process, uint Flags);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool SetThreadSelectedCpuSets(
            IntPtr Thread, uint[] CpuSetIds, uint CpuSetIdCount);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern UIntPtr SetThreadAffinityMask(
            IntPtr hThread, UIntPtr dwThreadAffinityMask);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetThreadGroupAffinity(
            IntPtr hThread, out GROUP_AFFINITY GroupAffinity);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetProcessAffinityMask(
            IntPtr hProcess, out UIntPtr lpProcessAffinityMask,
            out UIntPtr lpSystemAffinityMask);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool SetProcessAffinityMask(
            IntPtr hProcess, UIntPtr dwProcessAffinityMask);
    }
}
