//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelemetryVibShaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XCoordinate {
            get {
                return ((int)(this["XCoordinate"]));
            }
            set {
                this["XCoordinate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int YCoordinate {
            get {
                return ((int)(this["YCoordinate"]));
            }
            set {
                this["YCoordinate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int cmbAudioDevice1 {
            get {
                return ((int)(this["cmbAudioDevice1"]));
            }
            set {
                this["cmbAudioDevice1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkEnableAoASoundEffects1 {
            get {
                return ((bool)(this["chkEnableAoASoundEffects1"]));
            }
            set {
                this["chkEnableAoASoundEffects1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Office\\root\\Office16\\MEDIA\\APPLAUSE.WAV")]
        public string txtSoundEffect1 {
            get {
                return ((string)(this["txtSoundEffect1"]));
            }
            set {
                this["txtSoundEffect1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int trkVolumeMultiplier1 {
            get {
                return ((int)(this["trkVolumeMultiplier1"]));
            }
            set {
                this["trkVolumeMultiplier1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkEnableAoASoundEffects2 {
            get {
                return ((bool)(this["chkEnableAoASoundEffects2"]));
            }
            set {
                this["chkEnableAoASoundEffects2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Office\\root\\Office16\\MEDIA\\APPLAUSE.WAV")]
        public string txtSoundEffect2 {
            get {
                return ((string)(this["txtSoundEffect2"]));
            }
            set {
                this["txtSoundEffect2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int trkVolumeMultiplier2 {
            get {
                return ((int)(this["trkVolumeMultiplier2"]));
            }
            set {
                this["trkVolumeMultiplier2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string genericString {
            get {
                return ((string)(this["genericString"]));
            }
            set {
                this["genericString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int genericInt {
            get {
                return ((int)(this["genericInt"]));
            }
            set {
                this["genericInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool genericBool {
            get {
                return ((bool)(this["genericBool"]));
            }
            set {
                this["genericBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.249")]
        public string txtArduinoIP {
            get {
                return ((string)(this["txtArduinoIP"]));
            }
            set {
                this["txtArduinoIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54671")]
        public string txtArduinoPort {
            get {
                return ((string)(this["txtArduinoPort"]));
            }
            set {
                this["txtArduinoPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkVibrateMotorForSpeedBrake {
            get {
                return ((bool)(this["chkVibrateMotorForSpeedBrake"]));
            }
            set {
                this["chkVibrateMotorForSpeedBrake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkVibrateMotorForFlaps {
            get {
                return ((bool)(this["chkVibrateMotorForFlaps"]));
            }
            set {
                this["chkVibrateMotorForFlaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int numMinIntensitySpeedBrakes {
            get {
                return ((int)(this["numMinIntensitySpeedBrakes"]));
            }
            set {
                this["numMinIntensitySpeedBrakes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int numMaxIntensitySpeedBrakes {
            get {
                return ((int)(this["numMaxIntensitySpeedBrakes"]));
            }
            set {
                this["numMaxIntensitySpeedBrakes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int numMinIntensityFlaps {
            get {
                return ((int)(this["numMinIntensityFlaps"]));
            }
            set {
                this["numMinIntensityFlaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkTWatchVibrate {
            get {
                return ((bool)(this["chkTWatchVibrate"]));
            }
            set {
                this["chkTWatchVibrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkTWatchDisplayBackground {
            get {
                return ((bool)(this["chkTWatchDisplayBackground"]));
            }
            set {
                this["chkTWatchDisplayBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.248")]
        public string txtTWatchIP {
            get {
                return ((string)(this["txtTWatchIP"]));
            }
            set {
                this["txtTWatchIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54671")]
        public string txtTWatchPort {
            get {
                return ((string)(this["txtTWatchPort"]));
            }
            set {
                this["txtTWatchPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54671")]
        public string txtListeningPort {
            get {
                return ((string)(this["txtListeningPort"]));
            }
            set {
                this["txtListeningPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int trkEffectTimeout {
            get {
                return ((int)(this["trkEffectTimeout"]));
            }
            set {
                this["trkEffectTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ralch\\source\\repos\\UDPEchoServer1\\AoA_UDP_Server\\units.json")]
        public string txtJSON {
            get {
                return ((string)(this["txtJSON"]));
            }
            set {
                this["txtJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkChangeToMonitor {
            get {
                return ((bool)(this["chkChangeToMonitor"]));
            }
            set {
                this["chkChangeToMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkShowStatistics {
            get {
                return ((bool)(this["chkShowStatistics"]));
            }
            set {
                this["chkShowStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int numMaxIntensityFlaps {
            get {
                return ((int)(this["numMaxIntensityFlaps"]));
            }
            set {
                this["numMaxIntensityFlaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nudMinSpeed {
            get {
                return ((int)(this["nudMinSpeed"]));
            }
            set {
                this["nudMinSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBox1 {
            get {
                return ((int)(this["comboBox1"]));
            }
            set {
                this["comboBox1"] = value;
            }
        }
    }
}
